name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - name: Run ESLint
#      uses: hallee/eslint-action@1.0.1

      name: a job to say hello_world_job
      steps:
        - name: hello world action
          id: hello
          usess: jinjubei/ESLinter@v1
          with:
            who-to-greet: "Andy"
        - name: get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"