name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run ESLint
      uses: jinjubei/eslint-action@master #Touch
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        